openapi: 3.0.3
info:
  title: Coordinate API
  description: |-
    Coordinate API
  version: 1.0.0
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: Coordinate
    description: Endpoint of Coordinate
 
paths:
  /coorsinate:
    post:
      tags:
        - Coordinate
      summary: Search coordinate
      description: Add a new pet to the store
      operationId: addPet
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoordinateRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoordinateResponse'          


          
components:
  schemas:
    CoordinateRequest:
      type: object
    CoordinateResponse:
      type: object
      properties:
        youSent:
          type: object
          properties:
            latitude:
              type: number
              format: double
            longitude:
              type: number
              format: double
            weFound:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  latitude:
                    type: number
                    format: double
                  longitude:
                    type: number
                    format: double
